# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.private_key_path = File.expand_path('~/.vagrant.d/insecure_private_key')
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.define('seedbomb') do |config|
    # hostname
    config.vm.hostname =  'seedbomb'

    # forwards
    config.vm.network :forwarded_port, guest: 8001, host: 8001

    # memory & cpus
    config.vm.provider("virtualbox") do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end

    config.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = 'vagrant_provisioning/playbook.yml'
      ansible.sudo = true
      ansible.limit = 'all'
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    end
  end

end

